export const GET_ERRORS = 'GET_ERRORS';
export const USER_LOADING = 'USER_LOADING';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const NEW_USER = 'NEW_USER';

//MY OWN STATUS
export const INITIALIZE_STATUS = 'INITIALIZE_STATUS';
export const USER_LOGOUT = 'USER_LOGOUT';
export const GET_EXISTING_ATTENDEE = 'GET_EXISTING_ATTENDEE';